name: Deploy Java Web App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [Windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to Tomcat
      run: |
        $basicAuth = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("${env:TOMCAT_USERNAME}:${env:TOMCAT_PASSWORD}"))
        $url = "http://localhost:8081/manager/text/deploy?path=/your-app"
        $warFile = "C:\Users\rodrigo.r.alcaide\Desktop\Tarefa_TomCat\java-app\build\libs\java-app.war"

        $curlArgs = @("-u", $basicAuth, "--upload-file", $warFile, $url)
    
        curl @curlArgs
      env:
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
